### ISSUE TITLE
Extension now tries to give kudos to own activities

### ISSUE THREAD

**Issue by piaseq** [o2dazone/StravaKudos#28] opened 2021-08-01 09:22 UTC
There must have been a change in Strava frontend or there is a bug in the latest code as the extension now tries to give kudos to my own activities. This results in a popup opening and only refreshing the page gets rid of it:
![image](https://user-images.githubusercontent.com/11159401/127766035-bc39e092-197c-4252-8717-66022c5e7d71.png)

**Comment by firozzer** [comment] 2021-08-01 13:38
I don't know about the 'self-kudoing' thing, but for me the "Give x Kudos" button is not showing at all now. I see that new code has been pushed 2 days back, so it might have broken something. Following xpath on frontend works just fine: `//button[@title='Give Kudos']` to identify the Kudos buttons.

Those looking for a quick fix in the meantime can run the following in the console:

```
const sleep = ms => new Promise(res => setTimeout(res, ms));
let kudosBtns = document.querySelectorAll('button[title=\'Give Kudos\']')
for (let index = 0; index < kudosBtns.length; index++) {
    console.log("Kudoing");
    kudosBtns[index].click();
    await sleep(Math.random()*1000 + 500);
}
```

**Comment by o2dazone** [comment] 2021-08-01 16:18
Thanks for the report @piaseq, and thanks @XtremePwnership for digging into it a bit more!

This bug has been addressed, and there's more information in [this bug report](https://github.com/o2dazone/StravaKudos/issues/25) from a few days ago. Google has approved my latest changes to the extension, and it should auto-update for you. But if you're still having trouble, you can navigate to `chrome://extensions` and click "Update" at the top.

Closing this as it's a duplicate of https://github.com/o2dazone/StravaKudos/issues/25

**Closed as completed by o2dazone** 2021-08-01 16:18 UTC
