### ISSUE TITLE
Extension stopped working 

### ISSUE THREAD

**Issue by AlexM370** [o2dazone/StravaKudos#26] opened 2021-07-30 14:45 UTC
the extension has stopped working not sure if it was after the latest chrome update:
Version 92.0.4515.107 (Official Build) (64-bit)

Thanks!

**Comment by o2dazone** [comment] 2021-07-30 22:07
Thanks @AlexM370 - confirmed it's broken

Duplicate of https://github.com/o2dazone/StravaKudos/issues/25

**Closed as completed by o2dazone** 2021-07-30 22:07 UTC
