### ISSUE TITLE
Extension Broken?

### ISSUE THREAD

**Issue by edgemint** [o2dazone/StravaKudos#25] opened 2021-07-30 13:20 UTC
As of today, the extension doesn't seem to work anymore. The button is hidden, unhiding it via Inspect/Console shows "give 0 kudos". Update needed?

**Comment by MikeTuzylak** [comment] 2021-07-30 15:41
i'm getting the same issue. 
Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by tomschlong** [comment] 2021-07-30 15:51
Still working on Yandex Browser ver 21.6 Mobile Android

I used it earlier today on chrome desktop
But I can't say which version i have installed as I'm now out of office for
the next few weeks.

Did you make sure the extension is still active after the browser update?
Clear cookies etc?

**Comment by tomn-app** [comment] 2021-07-30 18:39
Yeah, I usually use it on Brave, so I re-tried it on actual Chrome(which is essentially completely fresh, it's mostly unused except for testing purposes) - same issue, after clearing browser history, installing/reinstalling extension.

Version 92.0.4515.107 (Official Build) (64-bit) for Chrome
Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit) for Brave

**Comment by o2dazone** [comment] 2021-07-30 22:06
Hey @torengen, 

Thanks for the heads up about the bug. I can confirm it is no longer working. Looks as though Strava has changed their UI, normally we're looking for 

```js
document.querySelectorAll('.activity button.js-add-kudo, .group-activity button.js-add-kudo');
```

but those elements no longer exist on the page. I'm thinking it's safe enough to rely on what I assume their unique identifiers for integration testing and use 

```js
document.querySelectorAll('[data-testid="kudos_button"]');
```

Let me do a bit of poking around to determine if this case will work for both single and group activities. If anyone has anymore analysis on what's happening, feel free to chime in.

Extra special thanks to @tomschlong for doing the initial triaging ⭐

**Comment by o2dazone** [comment] 2021-07-31 00:07
Hey @torengen, and anyone else following this thread

I've passed off the update of the extension to Google. It may take a while because I'm using the old v2 manifest, which requires additional review from their team.

![Screen Shot 2021-07-30 at 5 02 27 PM](https://user-images.githubusercontent.com/1907517/127722238-e593af8f-5aad-4c25-957e-5c20926d38f4.png)

In the mean time, I've cut a release and uploaded the built binaries on this repo

https://github.com/o2dazone/StravaKudos/releases/tag/v0.12

You are free to sideload the zip, crx or you can wait for the Web Store to approve my update. Let me know if you have any questions 👍 and thanks again for the bug report

**Comment by o2dazone** [comment] 2021-08-01 16:15
Re-opening this as others are also experiencing this bug. I'll close this once the confusion dies down lol

**Comment by o2dazone** [comment] 2021-08-01 16:21
Google has approved the latest extension changes, but if your extension is still not syncing automatically, you may need to navigate to `chrome://extensions` URL and click the "Update" button at the very top. The latest version should be "0.12"
![Untitled-3](https://user-images.githubusercontent.com/1907517/127778117-19fea9c1-116d-4cec-b62b-7709a9025794.png)

**Comment by piaseq** [comment] 2021-08-01 17:42
@o2dazone Unfortunately 0.12 still gives kudos to my own activities thus opening the popup and forcing to reload the page to get rid of it.

**Comment by o2dazone** [comment] 2021-08-01 17:47
Hey @piaseq, sorry this is still giving you trouble. Are you using the updated version from the Chrome Web Store, or did you sideload the CRX from GitHub? Can you double check that there are not multiple version of StravaKudos on your `chrome://extensions` page? Lastly, can you tell me what version of Google Chrome you are using?

**Comment by o2dazone** [comment] 2021-08-01 17:52
I was able to replicate the bug you're experiencing. I haven't been using Strava lately, but I can confirm with the one activity I did upload, that I am seeing the same thing as you. Let me get a fix out for it.

**Comment by piaseq** [comment] 2021-08-01 18:08
> Hey @piaseq, sorry this is still giving you trouble. Are you using the updated version from the Chrome Web Store, or did you sideload the CRX from GitHub? Can you double check that there are not multiple version of StravaKudos on your `chrome://extensions` page? Lastly, can you tell me what version of Google Chrome you are using?

Yes, everything's updated.

> I was able to replicate the bug you're experiencing. I haven't been using Strava lately, but I can confirm with the one activity I did upload, that I am seeing the same thing as you. Let me get a fix out for it.

Great :)  Thanks!

**Comment by o2dazone** [comment] 2021-08-01 21:23
Hey @piaseq and everyone else following this thread,

I've updated the code to now only Kudos activities that are not your own. Sorry for the delay, there were substantial changes to the Strava UI, and sometimes clever code can lead to bugs.

I've submitted an update to the extension for Google's Web Store approval. This process can take a day or two.
![Untitled-2](https://user-images.githubusercontent.com/1907517/127785680-a1286053-7e90-4bd3-bcca-db13473b0031.png)

I've also included the zip and crx binaries if you want to test it before it reaches the Web Store (Anyone who's comfortable with doing so, please report any bugs you may find in this thread).

https://github.com/o2dazone/StravaKudos/releases/tag/v0.13

**Comment by o2dazone** [comment] 2021-08-01 21:46
Whoa, well that was fast. The extension has been approved by Google. Latest version is 0.13 on the extension homepage

https://chrome.google.com/webstore/detail/strava-kudos/fmgpfcolhjopnnbklpambicfacbbhbac

**Comment by creid0611** [comment] 2021-08-02 09:48
Hi. I have downloaded the latest version of the extension and it no longer appears on my Strava page.
Do I need to do anything special to get it to reappear ?
When I look at the page code I see that the button status is hidden and the skCount is 0 even though I see new activities with no Kudos
Thanks for all you help and work on this fab extension
Chris

**Comment by piaseq** [comment] 2021-08-02 10:37
> Hey @piaseq and everyone else following this thread,
> 
> I've updated the code to now only Kudos activities that are not your own. Sorry for the delay, there were substantial changes to the Strava UI, and sometimes clever code can lead to bugs.
> 
> I've submitted an update to the extension for Google's Web Store approval. This process can take a day or two.
> ![Untitled-2](https://user-images.githubusercontent.com/1907517/127785680-a1286053-7e90-4bd3-bcca-db13473b0031.png)
> 
> I've also included the zip and crx binaries if you want to test it before it reaches the Web Store (Anyone who's comfortable with doing so, please report any bugs you may find in this thread).
> 
> https://github.com/o2dazone/StravaKudos/releases/tag/v0.13

It works :) Thank you!

**Comment by o2dazone** [comment] 2021-08-02 15:34
Hey @creid0611,

Was the extension working for you prior to the `v0.13` update? Can you give me some more details and perhaps take a screenshot of your devtools with the Elements tab open? I would like to examine the HTML of the page. I'm curious if there is an AB test running that is testing their new React changes.

**Comment by creid0611** [comment] 2021-08-02 15:46
> Hey @creid0611,
> 
> Was the extension working for you prior to the `v0.13` update? Can you give me some more details and perhaps take a screenshot of your devtools with the Elements tab open? I would like to examine the HTML of the page. I'm curious if there is an AB test running that is testing their new React changes.

Hi o2dazone,

Yeah. It was all working fine as of Friday last week (but I do not know what version of the extension that was).

I have loaded the extension v0.13 from the zip file and the button still does now show.

Please find attached a screenshot showing the Elements.

The bottom right has a couple of error/warnings. Not sure if they are relevant. "Failed to load resource".

There is also an issue which is on the second screenshot. "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform"

Hope these help

Regards
Chris
![strava_elements](https://user-images.githubusercontent.com/88318241/127888552-23bf09e2-c7af-4cdd-9a90-67da34746923.PNG)
![strava_elements_issue](https://user-images.githubusercontent.com/88318241/127888554-853ebe35-5cc5-43e1-aba6-9ff9e271000d.PNG)

**Comment by o2dazone** [comment] 2021-08-02 15:56
Awesome, thanks for the screenshots!

I believe those issues and the failing network request are from Strava, as my script doesn't interface with the `navigator` API

As for the button not appearing, this was exactly what people were experiencing before I rolled out the fixes to accommodate. Looking at your markup, it looks about the same as mine (except it looks like there's a `<noscript>` block in your markup that mine doesn't have. Do you run any other Strava extensions? I'm curious if there's a conflict.

Could you also give me a screenshot of the "Kudos" button? I want to make sure the markup matches with what I'm seeing. Here's an example.

![Screen Shot 2021-08-02 at 8 56 19 AM](https://user-images.githubusercontent.com/1907517/127889911-c1055ee9-3b4b-4b54-bd58-a510b1835639.png)

**Comment by creid0611** [comment] 2021-08-02 16:13
Here you go.
I hope this is what you were looking for.
I wasn't aware I had any one Strava scripts/extensions running
![strava_kudos_button](https://user-images.githubusercontent.com/88318241/127892115-4db9623e-f809-4aa6-a721-ffde65604c91.PNG)
![kudos_button_code](https://user-images.githubusercontent.com/88318241/127892118-fce1ca71-7623-485f-8315-373869b3824d.PNG)

**Comment by o2dazone** [comment] 2021-08-02 16:23
oooh, interesting! So it looks as though Strava might be A/B testing their new experience. Your markup references elements that no longer exist in the new experience, which is what the extension is made for. I'm starting my work day, but if you hold tight, I can bundle up the old extension for you and share it. You would have to side-load it, but at least it'll keep you operating until they roll the experience out full time.

**Comment by o2dazone** [comment] 2021-08-02 22:42
For anyone having trouble with the latest update of StravaKudos (@creid0611, @jimkeeble), I've posted instructions in an older thread on how to side-load the old version of the extension.

https://github.com/o2dazone/StravaKudos/issues/29

I'll keep these two issues open to address any questions or feedback for both the old version of StravaKudos, and the new one

**Comment by creid0611** [comment] 2021-08-05 07:39
Looks like I have been moved from A to B or B to A as the packaged version of the old code has stopped working this morning.
I went to the Chrome store and installed the latest version from there and it is working a treat now.
Thanks for all of your help
Chris

**Comment by o2dazone** [comment] 2021-08-05 16:04
Thanks for the update, Chris! Glad we were able to come up with a semi-hacky solution until folks got moved over to the new treatment.

**Closed as completed** 2022-07-02 19:23 UTC
Labels: bug
